name: Daily Churn Pipeline

on:
  schedule:
    - cron: '0 8 * * *'  # Runs every day at 8:00 AM UTC (1:30 PM IST)
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-churn-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas mysql-connector-python faker

    - name: Run churn pipeline script
      env:
        TIDB_HOST: ${{ secrets.TIDB_HOST }}
        TIDB_USER: ${{ secrets.TIDB_USER }}
        TIDB_PASSWORD: ${{ secrets.TIDB_PASSWORD }}
        TIDB_DATABASE: ${{ secrets.TIDB_DATABASE }}
      run: |
        python churn_pipeline.py
